import { resolve } from 'node:path';
import { defineConfig } from 'vite';
import dts from 'vite-plugin-dts';

export default defineConfig({
  plugins: [
    dts({
      include: ['src'],
      outDir: 'dist',
    }),
  ],
  build: {
    lib: {
      entry: {
        index: resolve(__dirname, 'src/index.ts'),
        define: resolve(__dirname, 'src/define.ts'),
        'components/data-display/kb-accordion-group.define': resolve(
          __dirname,
          'src/components/data-display/kb-accordion-group.define.ts',
        ),
        'components/data-display/kb-accordion.define': resolve(
          __dirname,
          'src/components/data-display/kb-accordion.define.ts',
        ),
        'components/data-display/kb-card.define': resolve(__dirname, 'src/components/data-display/kb-card.define.ts'),
        'components/data-display/kb-list-item.define': resolve(
          __dirname,
          'src/components/data-display/kb-list-item.define.ts',
        ),
        'components/data-display/kb-list.define': resolve(__dirname, 'src/components/data-display/kb-list.define.ts'),
        'components/data-display/kb-table.define': resolve(__dirname, 'src/components/data-display/kb-table.define.ts'),
        'components/data-display/kb-tag-group.define': resolve(
          __dirname,
          'src/components/data-display/kb-tag-group.define.ts',
        ),
        'components/data-display/kb-tag.define': resolve(__dirname, 'src/components/data-display/kb-tag.define.ts'),
        'components/feedback/kb-alert.define': resolve(__dirname, 'src/components/feedback/kb-alert.define.ts'),
        'components/feedback/kb-badge.define': resolve(__dirname, 'src/components/feedback/kb-badge.define.ts'),
        'components/feedback/kb-progress.define': resolve(__dirname, 'src/components/feedback/kb-progress.define.ts'),
        'components/feedback/kb-spinner.define': resolve(__dirname, 'src/components/feedback/kb-spinner.define.ts'),
        'components/feedback/kb-toast.define': resolve(__dirname, 'src/components/feedback/kb-toast.define.ts'),
        'components/forms/kb-button-group.define': resolve(__dirname, 'src/components/forms/kb-button-group.define.ts'),
        'components/forms/kb-button.define': resolve(__dirname, 'src/components/forms/kb-button.define.ts'),
        'components/forms/kb-checkbox-group.define': resolve(
          __dirname,
          'src/components/forms/kb-checkbox-group.define.ts',
        ),
        'components/forms/kb-checkbox.define': resolve(__dirname, 'src/components/forms/kb-checkbox.define.ts'),
        'components/forms/kb-form-control.define': resolve(__dirname, 'src/components/forms/kb-form-control.define.ts'),
        'components/forms/kb-form-label.define': resolve(__dirname, 'src/components/forms/kb-form-label.define.ts'),
        'components/forms/kb-icon-button.define': resolve(__dirname, 'src/components/forms/kb-icon-button.define.ts'),
        'components/forms/kb-input.define': resolve(__dirname, 'src/components/forms/kb-input.define.ts'),
        'components/forms/kb-radio-group.define': resolve(__dirname, 'src/components/forms/kb-radio-group.define.ts'),
        'components/forms/kb-radio.define': resolve(__dirname, 'src/components/forms/kb-radio.define.ts'),
        'components/forms/kb-select.define': resolve(__dirname, 'src/components/forms/kb-select.define.ts'),
        'components/forms/kb-switch.define': resolve(__dirname, 'src/components/forms/kb-switch.define.ts'),
        'components/forms/kb-textarea.define': resolve(__dirname, 'src/components/forms/kb-textarea.define.ts'),
        'components/layout/kb-box.define': resolve(__dirname, 'src/components/layout/kb-box.define.ts'),
        'components/layout/kb-container.define': resolve(__dirname, 'src/components/layout/kb-container.define.ts'),
        'components/layout/kb-divider.define': resolve(__dirname, 'src/components/layout/kb-divider.define.ts'),
        'components/layout/kb-flex.define': resolve(__dirname, 'src/components/layout/kb-flex.define.ts'),
        'components/layout/kb-grid.define': resolve(__dirname, 'src/components/layout/kb-grid.define.ts'),
        'components/layout/kb-stack.define': resolve(__dirname, 'src/components/layout/kb-stack.define.ts'),
        'components/navigation/kb-breadcrumb.define': resolve(
          __dirname,
          'src/components/navigation/kb-breadcrumb.define.ts',
        ),
        'components/navigation/kb-link.define': resolve(__dirname, 'src/components/navigation/kb-link.define.ts'),
        'components/navigation/kb-tabs.define': resolve(__dirname, 'src/components/navigation/kb-tabs.define.ts'),
        'components/overlay/kb-drawer.define': resolve(__dirname, 'src/components/overlay/kb-drawer.define.ts'),
        'components/overlay/kb-modal.define': resolve(__dirname, 'src/components/overlay/kb-modal.define.ts'),
        'components/overlay/kb-popover.define': resolve(__dirname, 'src/components/overlay/kb-popover.define.ts'),
        'components/overlay/kb-tooltip.define': resolve(__dirname, 'src/components/overlay/kb-tooltip.define.ts'),
        'components/typography/kb-code.define': resolve(__dirname, 'src/components/typography/kb-code.define.ts'),
        'components/typography/kb-heading.define': resolve(__dirname, 'src/components/typography/kb-heading.define.ts'),
        'components/typography/kb-text.define': resolve(__dirname, 'src/components/typography/kb-text.define.ts'),

        'core/theme': resolve(__dirname, 'src/core/theme.ts'),
        'core/recipe': resolve(__dirname, 'src/core/recipe.ts'),
        'utils/cx': resolve(__dirname, 'src/utils/cx.ts'),
        'react/index': resolve(__dirname, 'src/react/index.ts'),
        'components/data-display/kb-accordion': resolve(__dirname, 'src/components/data-display/kb-accordion.ts'),
        'components/data-display/kb-accordion-group': resolve(
          __dirname,
          'src/components/data-display/kb-accordion-group.ts',
        ),
        'components/data-display/kb-card': resolve(__dirname, 'src/components/data-display/kb-card.ts'),
        'components/data-display/kb-list': resolve(__dirname, 'src/components/data-display/kb-list.ts'),
        'components/data-display/kb-list-item': resolve(__dirname, 'src/components/data-display/kb-list-item.ts'),
        'components/data-display/kb-table': resolve(__dirname, 'src/components/data-display/kb-table.ts'),
        'components/data-display/kb-tag': resolve(__dirname, 'src/components/data-display/kb-tag.ts'),
        'components/data-display/kb-tag-group': resolve(__dirname, 'src/components/data-display/kb-tag-group.ts'),
        'components/feedback/kb-alert': resolve(__dirname, 'src/components/feedback/kb-alert.ts'),
        'components/feedback/kb-badge': resolve(__dirname, 'src/components/feedback/kb-badge.ts'),
        'components/feedback/kb-progress': resolve(__dirname, 'src/components/feedback/kb-progress.ts'),
        'components/feedback/kb-spinner': resolve(__dirname, 'src/components/feedback/kb-spinner.ts'),
        'components/feedback/kb-toast': resolve(__dirname, 'src/components/feedback/kb-toast.ts'),
        'components/forms/kb-button': resolve(__dirname, 'src/components/forms/kb-button.ts'),
        'components/forms/kb-button-group': resolve(__dirname, 'src/components/forms/kb-button-group.ts'),
        'components/forms/kb-checkbox': resolve(__dirname, 'src/components/forms/kb-checkbox.ts'),
        'components/forms/kb-checkbox-group': resolve(__dirname, 'src/components/forms/kb-checkbox-group.ts'),
        'components/forms/kb-form-control': resolve(__dirname, 'src/components/forms/kb-form-control.ts'),
        'components/forms/kb-form-label': resolve(__dirname, 'src/components/forms/kb-form-label.ts'),
        'components/forms/kb-icon-button': resolve(__dirname, 'src/components/forms/kb-icon-button.ts'),
        'components/forms/kb-input': resolve(__dirname, 'src/components/forms/kb-input.ts'),
        'components/forms/kb-radio': resolve(__dirname, 'src/components/forms/kb-radio.ts'),
        'components/forms/kb-radio-group': resolve(__dirname, 'src/components/forms/kb-radio-group.ts'),
        'components/forms/kb-select': resolve(__dirname, 'src/components/forms/kb-select.ts'),
        'components/forms/kb-switch': resolve(__dirname, 'src/components/forms/kb-switch.ts'),
        'components/forms/kb-textarea': resolve(__dirname, 'src/components/forms/kb-textarea.ts'),
        'components/layout/kb-box': resolve(__dirname, 'src/components/layout/kb-box.ts'),
        'components/layout/kb-container': resolve(__dirname, 'src/components/layout/kb-container.ts'),
        'components/layout/kb-divider': resolve(__dirname, 'src/components/layout/kb-divider.ts'),
        'components/layout/kb-flex': resolve(__dirname, 'src/components/layout/kb-flex.ts'),
        'components/layout/kb-grid': resolve(__dirname, 'src/components/layout/kb-grid.ts'),
        'components/layout/kb-stack': resolve(__dirname, 'src/components/layout/kb-stack.ts'),
        'components/navigation/kb-breadcrumb': resolve(__dirname, 'src/components/navigation/kb-breadcrumb.ts'),
        'components/navigation/kb-link': resolve(__dirname, 'src/components/navigation/kb-link.ts'),
        'components/navigation/kb-tabs': resolve(__dirname, 'src/components/navigation/kb-tabs.ts'),
        'components/overlay/kb-drawer': resolve(__dirname, 'src/components/overlay/kb-drawer.ts'),
        'components/overlay/kb-modal': resolve(__dirname, 'src/components/overlay/kb-modal.ts'),
        'components/overlay/kb-popover': resolve(__dirname, 'src/components/overlay/kb-popover.ts'),
        'components/overlay/kb-tooltip': resolve(__dirname, 'src/components/overlay/kb-tooltip.ts'),
        'components/typography/kb-code': resolve(__dirname, 'src/components/typography/kb-code.ts'),
        'components/typography/kb-heading': resolve(__dirname, 'src/components/typography/kb-heading.ts'),
        'components/typography/kb-text': resolve(__dirname, 'src/components/typography/kb-text.ts'),
      },
      formats: ['es'],
    },
    rollupOptions: {
      external: [/^lit(?:\/|$)/, '@lit/react', 'react'],
      output: {
        preserveModules: true,
        preserveModulesRoot: 'src',
        entryFileNames: '[name].js',
      },
    },
    target: 'ES2021',
    minify: false,
    sourcemap: true,
  },
});
