import { resolve } from 'node:path';
import { defineConfig } from 'vite';
import dts from 'vite-plugin-dts';

export default defineConfig({
  plugins: [
    dts({
      include: ['src'],
      outDir: 'dist',
    }),
  ],
  build: {
    lib: {
      entry: {
        index: resolve(__dirname, 'src/index.ts'),
        define: resolve(__dirname, 'src/define.ts'),
        'components/data-display/kb-accordion-group.define': resolve(
          __dirname,
          'src/components/data-display/kb-accordion-group.define.ts',
        ),
        'components/data-display/kb-accordion.define': resolve(
          __dirname,
          'src/components/data-display/kb-accordion.define.ts',
        ),
        'components/data-display/kb-card.define': resolve(__dirname, 'src/components/data-display/kb-card.define.ts'),
        'components/data-display/kb-list-item.define': resolve(
          __dirname,
          'src/components/data-display/kb-list-item.define.ts',
        ),
        'components/data-display/kb-list.define': resolve(__dirname, 'src/components/data-display/kb-list.define.ts'),
        'components/data-display/kb-table.define': resolve(__dirname, 'src/components/data-display/kb-table.define.ts'),
        'components/data-display/kb-tag-group.define': resolve(
          __dirname,
          'src/components/data-display/kb-tag-group.define.ts',
        ),
        'components/data-display/kb-tag.define': resolve(__dirname, 'src/components/data-display/kb-tag.define.ts'),
        'components/feedback/kb-alert.define': resolve(__dirname, 'src/components/feedback/kb-alert.define.ts'),
        'components/feedback/kb-badge.define': resolve(__dirname, 'src/components/feedback/kb-badge.define.ts'),
        'components/feedback/kb-progress.define': resolve(__dirname, 'src/components/feedback/kb-progress.define.ts'),
        'components/feedback/kb-spinner.define': resolve(__dirname, 'src/components/feedback/kb-spinner.define.ts'),
        'components/feedback/kb-toast.define': resolve(__dirname, 'src/components/feedback/kb-toast.define.ts'),
        'components/forms/kb-button-group.define': resolve(__dirname, 'src/components/forms/kb-button-group.define.ts'),
        'components/forms/kb-button.define': resolve(__dirname, 'src/components/forms/kb-button.define.ts'),
        'components/forms/kb-checkbox-group.define': resolve(
          __dirname,
          'src/components/forms/kb-checkbox-group.define.ts',
        ),
        'components/forms/kb-checkbox.define': resolve(__dirname, 'src/components/forms/kb-checkbox.define.ts'),
        'components/forms/kb-form-control.define': resolve(__dirname, 'src/components/forms/kb-form-control.define.ts'),
        'components/forms/kb-form-label.define': resolve(__dirname, 'src/components/forms/kb-form-label.define.ts'),
        'components/forms/kb-icon-button.define': resolve(__dirname, 'src/components/forms/kb-icon-button.define.ts'),
        'components/forms/kb-input.define': resolve(__dirname, 'src/components/forms/kb-input.define.ts'),
        'components/forms/kb-radio-group.define': resolve(__dirname, 'src/components/forms/kb-radio-group.define.ts'),
        'components/forms/kb-radio.define': resolve(__dirname, 'src/components/forms/kb-radio.define.ts'),
        'components/forms/kb-select.define': resolve(__dirname, 'src/components/forms/kb-select.define.ts'),
        'components/forms/kb-switch.define': resolve(__dirname, 'src/components/forms/kb-switch.define.ts'),
        'components/forms/kb-textarea.define': resolve(__dirname, 'src/components/forms/kb-textarea.define.ts'),
        'components/layout/kb-box.define': resolve(__dirname, 'src/components/layout/kb-box.define.ts'),
        'components/layout/kb-container.define': resolve(__dirname, 'src/components/layout/kb-container.define.ts'),
        'components/layout/kb-divider.define': resolve(__dirname, 'src/components/layout/kb-divider.define.ts'),
        'components/layout/kb-flex.define': resolve(__dirname, 'src/components/layout/kb-flex.define.ts'),
        'components/layout/kb-grid.define': resolve(__dirname, 'src/components/layout/kb-grid.define.ts'),
        'components/layout/kb-stack.define': resolve(__dirname, 'src/components/layout/kb-stack.define.ts'),
        'components/navigation/kb-breadcrumb.define': resolve(
          __dirname,
          'src/components/navigation/kb-breadcrumb.define.ts',
        ),
        'components/navigation/kb-link.define': resolve(__dirname, 'src/components/navigation/kb-link.define.ts'),
        'components/navigation/kb-tabs.define': resolve(__dirname, 'src/components/navigation/kb-tabs.define.ts'),
        'components/overlay/kb-drawer.define': resolve(__dirname, 'src/components/overlay/kb-drawer.define.ts'),
        'components/overlay/kb-modal.define': resolve(__dirname, 'src/components/overlay/kb-modal.define.ts'),
        'components/overlay/kb-popover.define': resolve(__dirname, 'src/components/overlay/kb-popover.define.ts'),
        'components/overlay/kb-tooltip.define': resolve(__dirname, 'src/components/overlay/kb-tooltip.define.ts'),
        'components/typography/kb-code.define': resolve(__dirname, 'src/components/typography/kb-code.define.ts'),
        'components/typography/kb-heading.define': resolve(__dirname, 'src/components/typography/kb-heading.define.ts'),
        'components/typography/kb-text.define': resolve(__dirname, 'src/components/typography/kb-text.define.ts'),

        'core/theme': resolve(__dirname, 'src/core/theme.ts'),
        'core/recipe': resolve(__dirname, 'src/core/recipe.ts'),
        'utils/cx': resolve(__dirname, 'src/utils/cx.ts'),
        'react/index': resolve(__dirname, 'src/react/index.ts'),
        'vue/index': resolve(__dirname, 'src/vue/index.ts'),
        'components/data-display/kb-accordion': resolve(__dirname, 'src/components/data-display/kb-accordion.ts'),
        'components/data-display/kb-accordion-group': resolve(
          __dirname,
          'src/components/data-display/kb-accordion-group.ts',
        ),
        'components/data-display/kb-card': resolve(__dirname, 'src/components/data-display/kb-card.ts'),
        'components/data-display/kb-list': resolve(__dirname, 'src/components/data-display/kb-list.ts'),
        'components/data-display/kb-list-item': resolve(__dirname, 'src/components/data-display/kb-list-item.ts'),
        'components/data-display/kb-table': resolve(__dirname, 'src/components/data-display/kb-table.ts'),
        'components/data-display/kb-tag': resolve(__dirname, 'src/components/data-display/kb-tag.ts'),
        'components/data-display/kb-tag-group': resolve(__dirname, 'src/components/data-display/kb-tag-group.ts'),
        'components/feedback/kb-alert': resolve(__dirname, 'src/components/feedback/kb-alert.ts'),
        'components/feedback/kb-badge': resolve(__dirname, 'src/components/feedback/kb-badge.ts'),
        'components/feedback/kb-progress': resolve(__dirname, 'src/components/feedback/kb-progress.ts'),
        'components/feedback/kb-spinner': resolve(__dirname, 'src/components/feedback/kb-spinner.ts'),
        'components/feedback/kb-toast': resolve(__dirname, 'src/components/feedback/kb-toast.ts'),
        'components/forms/kb-button': resolve(__dirname, 'src/components/forms/kb-button.ts'),
        'components/forms/kb-button-group': resolve(__dirname, 'src/components/forms/kb-button-group.ts'),
        'components/forms/kb-checkbox': resolve(__dirname, 'src/components/forms/kb-checkbox.ts'),
        'components/forms/kb-checkbox-group': resolve(__dirname, 'src/components/forms/kb-checkbox-group.ts'),
        'components/forms/kb-form-control': resolve(__dirname, 'src/components/forms/kb-form-control.ts'),
        'components/forms/kb-form-label': resolve(__dirname, 'src/components/forms/kb-form-label.ts'),
        'components/forms/kb-icon-button': resolve(__dirname, 'src/components/forms/kb-icon-button.ts'),
        'components/forms/kb-input': resolve(__dirname, 'src/components/forms/kb-input.ts'),
        'components/forms/kb-radio': resolve(__dirname, 'src/components/forms/kb-radio.ts'),
        'components/forms/kb-radio-group': resolve(__dirname, 'src/components/forms/kb-radio-group.ts'),
        'components/forms/kb-select': resolve(__dirname, 'src/components/forms/kb-select.ts'),
        'components/forms/kb-switch': resolve(__dirname, 'src/components/forms/kb-switch.ts'),
        'components/forms/kb-textarea': resolve(__dirname, 'src/components/forms/kb-textarea.ts'),
        'components/layout/kb-box': resolve(__dirname, 'src/components/layout/kb-box.ts'),
        'components/layout/kb-container': resolve(__dirname, 'src/components/layout/kb-container.ts'),
        'components/layout/kb-divider': resolve(__dirname, 'src/components/layout/kb-divider.ts'),
        'components/layout/kb-flex': resolve(__dirname, 'src/components/layout/kb-flex.ts'),
        'components/layout/kb-grid': resolve(__dirname, 'src/components/layout/kb-grid.ts'),
        'components/layout/kb-stack': resolve(__dirname, 'src/components/layout/kb-stack.ts'),
        'components/navigation/kb-breadcrumb': resolve(__dirname, 'src/components/navigation/kb-breadcrumb.ts'),
        'components/navigation/kb-link': resolve(__dirname, 'src/components/navigation/kb-link.ts'),
        'components/navigation/kb-tabs': resolve(__dirname, 'src/components/navigation/kb-tabs.ts'),
        'components/overlay/kb-drawer': resolve(__dirname, 'src/components/overlay/kb-drawer.ts'),
        'components/overlay/kb-modal': resolve(__dirname, 'src/components/overlay/kb-modal.ts'),
        'components/overlay/kb-popover': resolve(__dirname, 'src/components/overlay/kb-popover.ts'),
        'components/overlay/kb-tooltip': resolve(__dirname, 'src/components/overlay/kb-tooltip.ts'),
        'components/typography/kb-code': resolve(__dirname, 'src/components/typography/kb-code.ts'),
        'components/typography/kb-heading': resolve(__dirname, 'src/components/typography/kb-heading.ts'),
        'components/typography/kb-text': resolve(__dirname, 'src/components/typography/kb-text.ts'),

        // Phase 1 components
        'components/data-display/kb-avatar.define': resolve(
          __dirname,
          'src/components/data-display/kb-avatar.define.ts',
        ),
        'components/data-display/kb-avatar-group.define': resolve(
          __dirname,
          'src/components/data-display/kb-avatar-group.define.ts',
        ),
        'components/data-display/kb-kbd.define': resolve(__dirname, 'src/components/data-display/kb-kbd.define.ts'),
        'components/data-display/kb-stat.define': resolve(__dirname, 'src/components/data-display/kb-stat.define.ts'),
        'components/feedback/kb-skeleton.define': resolve(__dirname, 'src/components/feedback/kb-skeleton.define.ts'),
        'components/navigation/kb-pagination.define': resolve(
          __dirname,
          'src/components/navigation/kb-pagination.define.ts',
        ),
        'components/data-display/kb-avatar': resolve(__dirname, 'src/components/data-display/kb-avatar.ts'),
        'components/data-display/kb-avatar-group': resolve(__dirname, 'src/components/data-display/kb-avatar-group.ts'),
        'components/data-display/kb-kbd': resolve(__dirname, 'src/components/data-display/kb-kbd.ts'),
        'components/data-display/kb-stat': resolve(__dirname, 'src/components/data-display/kb-stat.ts'),
        'components/feedback/kb-skeleton': resolve(__dirname, 'src/components/feedback/kb-skeleton.ts'),
        'components/navigation/kb-pagination': resolve(__dirname, 'src/components/navigation/kb-pagination.ts'),

        // Phase 2 components
        'components/data-display/kb-collapsible.define': resolve(
          __dirname,
          'src/components/data-display/kb-collapsible.define.ts',
        ),
        'components/forms/kb-number-input.define': resolve(__dirname, 'src/components/forms/kb-number-input.define.ts'),
        'components/forms/kb-slider.define': resolve(__dirname, 'src/components/forms/kb-slider.define.ts'),
        'components/forms/kb-pin-input.define': resolve(__dirname, 'src/components/forms/kb-pin-input.define.ts'),
        'components/navigation/kb-steps.define': resolve(__dirname, 'src/components/navigation/kb-steps.define.ts'),
        'components/navigation/kb-step.define': resolve(__dirname, 'src/components/navigation/kb-step.define.ts'),
        'components/overlay/kb-dropdown-menu.define': resolve(
          __dirname,
          'src/components/overlay/kb-dropdown-menu.define.ts',
        ),
        'components/overlay/kb-menu-item.define': resolve(__dirname, 'src/components/overlay/kb-menu-item.define.ts'),
        'components/data-display/kb-collapsible': resolve(__dirname, 'src/components/data-display/kb-collapsible.ts'),
        'components/forms/kb-number-input': resolve(__dirname, 'src/components/forms/kb-number-input.ts'),
        'components/forms/kb-slider': resolve(__dirname, 'src/components/forms/kb-slider.ts'),
        'components/forms/kb-pin-input': resolve(__dirname, 'src/components/forms/kb-pin-input.ts'),
        'components/navigation/kb-steps': resolve(__dirname, 'src/components/navigation/kb-steps.ts'),
        'components/navigation/kb-step': resolve(__dirname, 'src/components/navigation/kb-step.ts'),
        'components/overlay/kb-dropdown-menu': resolve(__dirname, 'src/components/overlay/kb-dropdown-menu.ts'),
        'components/overlay/kb-menu-item': resolve(__dirname, 'src/components/overlay/kb-menu-item.ts'),

        // Phase 3 components
        'components/forms/kb-rating.define': resolve(__dirname, 'src/components/forms/kb-rating.define.ts'),
        'components/forms/kb-segment.define': resolve(__dirname, 'src/components/forms/kb-segment.define.ts'),
        'components/forms/kb-tags-input.define': resolve(__dirname, 'src/components/forms/kb-tags-input.define.ts'),
        'components/forms/kb-file-upload.define': resolve(__dirname, 'src/components/forms/kb-file-upload.define.ts'),
        'components/forms/kb-time-picker.define': resolve(__dirname, 'src/components/forms/kb-time-picker.define.ts'),
        'components/forms/kb-combobox.define': resolve(__dirname, 'src/components/forms/kb-combobox.define.ts'),
        'components/forms/kb-date-picker.define': resolve(__dirname, 'src/components/forms/kb-date-picker.define.ts'),
        'components/forms/kb-rating': resolve(__dirname, 'src/components/forms/kb-rating.ts'),
        'components/forms/kb-segment': resolve(__dirname, 'src/components/forms/kb-segment.ts'),
        'components/forms/kb-tags-input': resolve(__dirname, 'src/components/forms/kb-tags-input.ts'),
        'components/forms/kb-file-upload': resolve(__dirname, 'src/components/forms/kb-file-upload.ts'),
        'components/forms/kb-time-picker': resolve(__dirname, 'src/components/forms/kb-time-picker.ts'),
        'components/forms/kb-combobox': resolve(__dirname, 'src/components/forms/kb-combobox.ts'),
        'components/forms/kb-date-picker': resolve(__dirname, 'src/components/forms/kb-date-picker.ts'),

        // Phase 4 components
        'components/forms/kb-color-picker.define': resolve(__dirname, 'src/components/forms/kb-color-picker.define.ts'),
        'components/forms/kb-editable.define': resolve(__dirname, 'src/components/forms/kb-editable.define.ts'),
        'components/data-display/kb-tree-view.define': resolve(
          __dirname,
          'src/components/data-display/kb-tree-view.define.ts',
        ),
        'components/data-display/kb-timeline.define': resolve(
          __dirname,
          'src/components/data-display/kb-timeline.define.ts',
        ),
        'components/data-display/kb-carousel.define': resolve(
          __dirname,
          'src/components/data-display/kb-carousel.define.ts',
        ),
        'components/feedback/kb-clipboard.define': resolve(__dirname, 'src/components/feedback/kb-clipboard.define.ts'),
        'components/forms/kb-color-picker': resolve(__dirname, 'src/components/forms/kb-color-picker.ts'),
        'components/forms/kb-editable': resolve(__dirname, 'src/components/forms/kb-editable.ts'),
        'components/data-display/kb-tree-view': resolve(__dirname, 'src/components/data-display/kb-tree-view.ts'),
        'components/data-display/kb-timeline': resolve(__dirname, 'src/components/data-display/kb-timeline.ts'),
        'components/data-display/kb-carousel': resolve(__dirname, 'src/components/data-display/kb-carousel.ts'),
        'components/feedback/kb-clipboard': resolve(__dirname, 'src/components/feedback/kb-clipboard.ts'),

        // Phase 5 components
        'components/overlay/kb-alert-dialog.define': resolve(
          __dirname,
          'src/components/overlay/kb-alert-dialog.define.ts',
        ),
        'components/overlay/kb-context-menu.define': resolve(
          __dirname,
          'src/components/overlay/kb-context-menu.define.ts',
        ),
        'components/overlay/kb-hover-card.define': resolve(__dirname, 'src/components/overlay/kb-hover-card.define.ts'),
        'components/data-display/kb-data-list.define': resolve(
          __dirname,
          'src/components/data-display/kb-data-list.define.ts',
        ),
        'components/feedback/kb-empty-state.define': resolve(
          __dirname,
          'src/components/feedback/kb-empty-state.define.ts',
        ),
        'components/feedback/kb-circular-progress.define': resolve(
          __dirname,
          'src/components/feedback/kb-circular-progress.define.ts',
        ),
        'components/typography/kb-blockquote.define': resolve(
          __dirname,
          'src/components/typography/kb-blockquote.define.ts',
        ),
        'components/typography/kb-highlight.define': resolve(
          __dirname,
          'src/components/typography/kb-highlight.define.ts',
        ),
        'components/layout/kb-scroll-area.define': resolve(__dirname, 'src/components/layout/kb-scroll-area.define.ts'),
        'components/overlay/kb-alert-dialog': resolve(__dirname, 'src/components/overlay/kb-alert-dialog.ts'),
        'components/overlay/kb-context-menu': resolve(__dirname, 'src/components/overlay/kb-context-menu.ts'),
        'components/overlay/kb-hover-card': resolve(__dirname, 'src/components/overlay/kb-hover-card.ts'),
        'components/data-display/kb-data-list': resolve(__dirname, 'src/components/data-display/kb-data-list.ts'),
        'components/feedback/kb-empty-state': resolve(__dirname, 'src/components/feedback/kb-empty-state.ts'),
        'components/feedback/kb-circular-progress': resolve(
          __dirname,
          'src/components/feedback/kb-circular-progress.ts',
        ),
        'components/typography/kb-blockquote': resolve(__dirname, 'src/components/typography/kb-blockquote.ts'),
        'components/typography/kb-highlight': resolve(__dirname, 'src/components/typography/kb-highlight.ts'),
        'components/layout/kb-scroll-area': resolve(__dirname, 'src/components/layout/kb-scroll-area.ts'),

        // React wrappers (Phase 1-5)
        'react/components/kb-avatar': resolve(__dirname, 'src/react/components/kb-avatar.ts'),
        'react/components/kb-avatar-group': resolve(__dirname, 'src/react/components/kb-avatar-group.ts'),
        'react/components/kb-kbd': resolve(__dirname, 'src/react/components/kb-kbd.ts'),
        'react/components/kb-stat': resolve(__dirname, 'src/react/components/kb-stat.ts'),
        'react/components/kb-skeleton': resolve(__dirname, 'src/react/components/kb-skeleton.ts'),
        'react/components/kb-pagination': resolve(__dirname, 'src/react/components/kb-pagination.ts'),
        'react/components/kb-collapsible': resolve(__dirname, 'src/react/components/kb-collapsible.ts'),
        'react/components/kb-number-input': resolve(__dirname, 'src/react/components/kb-number-input.ts'),
        'react/components/kb-slider': resolve(__dirname, 'src/react/components/kb-slider.ts'),
        'react/components/kb-pin-input': resolve(__dirname, 'src/react/components/kb-pin-input.ts'),
        'react/components/kb-steps': resolve(__dirname, 'src/react/components/kb-steps.ts'),
        'react/components/kb-step': resolve(__dirname, 'src/react/components/kb-step.ts'),
        'react/components/kb-dropdown-menu': resolve(__dirname, 'src/react/components/kb-dropdown-menu.ts'),
        'react/components/kb-menu-item': resolve(__dirname, 'src/react/components/kb-menu-item.ts'),
        'react/components/kb-rating': resolve(__dirname, 'src/react/components/kb-rating.ts'),
        'react/components/kb-segment': resolve(__dirname, 'src/react/components/kb-segment.ts'),
        'react/components/kb-tags-input': resolve(__dirname, 'src/react/components/kb-tags-input.ts'),
        'react/components/kb-file-upload': resolve(__dirname, 'src/react/components/kb-file-upload.ts'),
        'react/components/kb-time-picker': resolve(__dirname, 'src/react/components/kb-time-picker.ts'),
        'react/components/kb-combobox': resolve(__dirname, 'src/react/components/kb-combobox.ts'),
        'react/components/kb-date-picker': resolve(__dirname, 'src/react/components/kb-date-picker.ts'),
        'react/components/kb-color-picker': resolve(__dirname, 'src/react/components/kb-color-picker.ts'),
        'react/components/kb-editable': resolve(__dirname, 'src/react/components/kb-editable.ts'),
        'react/components/kb-tree-view': resolve(__dirname, 'src/react/components/kb-tree-view.ts'),
        'react/components/kb-timeline': resolve(__dirname, 'src/react/components/kb-timeline.ts'),
        'react/components/kb-carousel': resolve(__dirname, 'src/react/components/kb-carousel.ts'),
        'react/components/kb-clipboard': resolve(__dirname, 'src/react/components/kb-clipboard.ts'),
        'react/components/kb-alert-dialog': resolve(__dirname, 'src/react/components/kb-alert-dialog.ts'),
        'react/components/kb-context-menu': resolve(__dirname, 'src/react/components/kb-context-menu.ts'),
        'react/components/kb-hover-card': resolve(__dirname, 'src/react/components/kb-hover-card.ts'),
        'react/components/kb-data-list': resolve(__dirname, 'src/react/components/kb-data-list.ts'),
        'react/components/kb-empty-state': resolve(__dirname, 'src/react/components/kb-empty-state.ts'),
        'react/components/kb-circular-progress': resolve(__dirname, 'src/react/components/kb-circular-progress.ts'),
        'react/components/kb-blockquote': resolve(__dirname, 'src/react/components/kb-blockquote.ts'),
        'react/components/kb-highlight': resolve(__dirname, 'src/react/components/kb-highlight.ts'),
        'react/components/kb-scroll-area': resolve(__dirname, 'src/react/components/kb-scroll-area.ts'),
        'vue/components/kb-input': resolve(__dirname, 'src/vue/components/kb-input.ts'),
        'vue/components/kb-textarea': resolve(__dirname, 'src/vue/components/kb-textarea.ts'),
        'vue/components/kb-select': resolve(__dirname, 'src/vue/components/kb-select.ts'),
        'vue/components/kb-checkbox': resolve(__dirname, 'src/vue/components/kb-checkbox.ts'),
        'vue/components/kb-switch': resolve(__dirname, 'src/vue/components/kb-switch.ts'),
      },
      formats: ['es'],
    },
    rollupOptions: {
      external: [/^lit(?:\/|$)/, '@lit/react', 'react', 'tailwind-merge', 'vue'],
      output: {
        preserveModules: true,
        preserveModulesRoot: 'src',
        entryFileNames: '[name].js',
      },
    },
    target: 'ES2021',
    minify: false,
    sourcemap: true,
  },
});
