import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  docs: [
    {
      type: 'category',
      label: 'Getting Started',
      collapsed: false,
      link: { type: 'doc', id: 'getting-started/installation' },
      items: [
        'getting-started/installation',
        'getting-started/setup-react',
        'getting-started/setup-vue',
        'getting-started/setup-svelte',
        'getting-started/setup-vanilla',
        'getting-started/dark-mode',
      ],
    },
    {
      type: 'category',
      label: 'Design System',
      collapsed: false,
      link: { type: 'doc', id: 'design-system/overview' },
      items: [
        'design-system/overview',
        'design-system/theming',
      ],
    },
    {
      type: 'category',
      label: 'Components',
      collapsed: false,
      link: { type: 'doc', id: 'components/overview' },
      items: [
        'components/overview',
      {
        type: 'category',
        label: 'Forms',
        collapsed: false,
        link: { type: 'generated-index', description: 'Forms components in KarbitUI.' },
        items: [
        'components/forms/button',
        'components/forms/button-group',
        'components/forms/icon-button',
        'components/forms/input',
        'components/forms/textarea',
        'components/forms/number-input',
        'components/forms/pin-input',
        'components/forms/checkbox',
        'components/forms/checkbox-group',
        'components/forms/radio',
        'components/forms/radio-group',
        'components/forms/switch',
        'components/forms/select',
        'components/forms/combobox',
        'components/forms/slider',
        'components/forms/rating',
        'components/forms/date-picker',
        'components/forms/time-picker',
        'components/forms/color-picker',
        'components/forms/file-upload',
        'components/forms/editable',
        'components/forms/tags-input',
        'components/forms/segment',
        'components/forms/form-control',
        'components/forms/form-label',
        ],
      },
      {
        type: 'category',
        label: 'Data Display',
        collapsed: false,
        link: { type: 'generated-index', description: 'Data Display components in KarbitUI.' },
        items: [
        'components/data-display/accordion',
        'components/data-display/accordion-group',
        'components/data-display/avatar',
        'components/data-display/avatar-group',
        'components/data-display/card',
        'components/data-display/carousel',
        'components/data-display/collapsible',
        'components/data-display/data-list',
        'components/data-display/kbd',
        'components/data-display/list',
        'components/data-display/list-item',
        'components/data-display/stat',
        'components/data-display/table',
        'components/data-display/tag',
        'components/data-display/tag-group',
        'components/data-display/timeline',
        'components/data-display/tree-view',
        ],
      },
      {
        type: 'category',
        label: 'Feedback',
        collapsed: false,
        link: { type: 'generated-index', description: 'Feedback components in KarbitUI.' },
        items: [
        'components/feedback/alert',
        'components/feedback/badge',
        'components/feedback/circular-progress',
        'components/feedback/clipboard',
        'components/feedback/empty-state',
        'components/feedback/progress',
        'components/feedback/skeleton',
        'components/feedback/spinner',
        'components/feedback/toast',
        ],
      },
      {
        type: 'category',
        label: 'Layout',
        collapsed: false,
        link: { type: 'generated-index', description: 'Layout components in KarbitUI.' },
        items: [
        'components/layout/box',
        'components/layout/container',
        'components/layout/divider',
        'components/layout/flex',
        'components/layout/grid',
        'components/layout/scroll-area',
        'components/layout/stack',
        ],
      },
      {
        type: 'category',
        label: 'Navigation',
        collapsed: false,
        link: { type: 'generated-index', description: 'Navigation components in KarbitUI.' },
        items: [
        'components/navigation/breadcrumb',
        'components/navigation/link',
        'components/navigation/pagination',
        'components/navigation/steps',
        'components/navigation/step',
        'components/navigation/tabs',
        ],
      },
      {
        type: 'category',
        label: 'Overlay',
        collapsed: false,
        link: { type: 'generated-index', description: 'Overlay components in KarbitUI.' },
        items: [
        'components/overlay/alert-dialog',
        'components/overlay/context-menu',
        'components/overlay/drawer',
        'components/overlay/dropdown-menu',
        'components/overlay/hover-card',
        'components/overlay/menu-item',
        'components/overlay/modal',
        'components/overlay/popover',
        'components/overlay/tooltip',
        ],
      },
      {
        type: 'category',
        label: 'Typography',
        collapsed: false,
        link: { type: 'generated-index', description: 'Typography components in KarbitUI.' },
        items: [
        'components/typography/blockquote',
        'components/typography/code',
        'components/typography/heading',
        'components/typography/highlight',
        'components/typography/text',
        ],
      },
      ],
    },
  ],
};

export default sidebars;
