import { KbAccordion } from './components/data-display/kb-accordion.js';
import { KbAccordionGroup } from './components/data-display/kb-accordion-group.js';
import { KbAvatar } from './components/data-display/kb-avatar.js';
import { KbAvatarGroup } from './components/data-display/kb-avatar-group.js';
import { KbCard } from './components/data-display/kb-card.js';
import { KbCarousel } from './components/data-display/kb-carousel.js';
import { KbCollapsible } from './components/data-display/kb-collapsible.js';
import { KbDataList } from './components/data-display/kb-data-list.js';
import { KbKbd } from './components/data-display/kb-kbd.js';
import { KbList } from './components/data-display/kb-list.js';
import { KbListItem } from './components/data-display/kb-list-item.js';
import { KbStat } from './components/data-display/kb-stat.js';
import { KbTable } from './components/data-display/kb-table.js';
import { KbTag } from './components/data-display/kb-tag.js';
import { KbTagGroup } from './components/data-display/kb-tag-group.js';
import { KbTimeline } from './components/data-display/kb-timeline.js';
import { KbTreeView } from './components/data-display/kb-tree-view.js';
import { KbAlert } from './components/feedback/kb-alert.js';
import { KbBadge } from './components/feedback/kb-badge.js';
import { KbCircularProgress } from './components/feedback/kb-circular-progress.js';
import { KbClipboard } from './components/feedback/kb-clipboard.js';
import { KbEmptyState } from './components/feedback/kb-empty-state.js';
import { KbProgress } from './components/feedback/kb-progress.js';
import { KbSkeleton } from './components/feedback/kb-skeleton.js';
import { KbSpinner } from './components/feedback/kb-spinner.js';
import { KbToast } from './components/feedback/kb-toast.js';
import { KbButton } from './components/forms/kb-button.js';
import { KbButtonGroup } from './components/forms/kb-button-group.js';
import { KbCheckbox } from './components/forms/kb-checkbox.js';
import { KbCheckboxGroup } from './components/forms/kb-checkbox-group.js';
import { KbColorPicker } from './components/forms/kb-color-picker.js';
import { KbCombobox } from './components/forms/kb-combobox.js';
import { KbDatePicker } from './components/forms/kb-date-picker.js';
import { KbEditable } from './components/forms/kb-editable.js';
import { KbFileUpload } from './components/forms/kb-file-upload.js';
import { KbFormControl } from './components/forms/kb-form-control.js';
import { KbFormLabel } from './components/forms/kb-form-label.js';
import { KbIconButton } from './components/forms/kb-icon-button.js';
import { KbInput } from './components/forms/kb-input.js';
import { KbNumberInput } from './components/forms/kb-number-input.js';
import { KbPinInput } from './components/forms/kb-pin-input.js';
import { KbRadio } from './components/forms/kb-radio.js';
import { KbRadioGroup } from './components/forms/kb-radio-group.js';
import { KbRating } from './components/forms/kb-rating.js';
import { KbSegment } from './components/forms/kb-segment.js';
import { KbSelect } from './components/forms/kb-select.js';
import { KbSlider } from './components/forms/kb-slider.js';
import { KbSwitch } from './components/forms/kb-switch.js';
import { KbTagsInput } from './components/forms/kb-tags-input.js';
import { KbTextarea } from './components/forms/kb-textarea.js';
import { KbTimePicker } from './components/forms/kb-time-picker.js';
import { KbBox } from './components/layout/kb-box.js';
import { KbContainer } from './components/layout/kb-container.js';
import { KbDivider } from './components/layout/kb-divider.js';
import { KbFlex } from './components/layout/kb-flex.js';
import { KbGrid } from './components/layout/kb-grid.js';
import { KbScrollArea } from './components/layout/kb-scroll-area.js';
import { KbStack } from './components/layout/kb-stack.js';
import { KbBreadcrumb } from './components/navigation/kb-breadcrumb.js';
import { KbLink } from './components/navigation/kb-link.js';
import { KbPagination } from './components/navigation/kb-pagination.js';
import { KbStep } from './components/navigation/kb-step.js';
import { KbSteps } from './components/navigation/kb-steps.js';
import { KbTabs } from './components/navigation/kb-tabs.js';
import { KbAlertDialog } from './components/overlay/kb-alert-dialog.js';
import { KbContextMenu } from './components/overlay/kb-context-menu.js';
import { KbDrawer } from './components/overlay/kb-drawer.js';
import { KbDropdownMenu } from './components/overlay/kb-dropdown-menu.js';
import { KbHoverCard } from './components/overlay/kb-hover-card.js';
import { KbMenuItem } from './components/overlay/kb-menu-item.js';
import { KbModal } from './components/overlay/kb-modal.js';
import { KbPopover } from './components/overlay/kb-popover.js';
import { KbTooltip } from './components/overlay/kb-tooltip.js';
import { KbBlockquote } from './components/typography/kb-blockquote.js';
import { KbCode } from './components/typography/kb-code.js';
import { KbHeading } from './components/typography/kb-heading.js';
import { KbHighlight } from './components/typography/kb-highlight.js';
import { KbText } from './components/typography/kb-text.js';
import { define } from './core/define.js';

define('kb-accordion', KbAccordion);
define('kb-accordion-group', KbAccordionGroup);
define('kb-avatar', KbAvatar);
define('kb-avatar-group', KbAvatarGroup);
define('kb-card', KbCard);
define('kb-carousel', KbCarousel);
define('kb-collapsible', KbCollapsible);
define('kb-data-list', KbDataList);
define('kb-kbd', KbKbd);
define('kb-list', KbList);
define('kb-list-item', KbListItem);
define('kb-stat', KbStat);
define('kb-table', KbTable);
define('kb-tag', KbTag);
define('kb-tag-group', KbTagGroup);
define('kb-timeline', KbTimeline);
define('kb-tree-view', KbTreeView);
define('kb-alert', KbAlert);
define('kb-badge', KbBadge);
define('kb-circular-progress', KbCircularProgress);
define('kb-clipboard', KbClipboard);
define('kb-empty-state', KbEmptyState);
define('kb-progress', KbProgress);
define('kb-skeleton', KbSkeleton);
define('kb-spinner', KbSpinner);
define('kb-toast', KbToast);
define('kb-button', KbButton);
define('kb-button-group', KbButtonGroup);
define('kb-checkbox', KbCheckbox);
define('kb-checkbox-group', KbCheckboxGroup);
define('kb-color-picker', KbColorPicker);
define('kb-combobox', KbCombobox);
define('kb-date-picker', KbDatePicker);
define('kb-editable', KbEditable);
define('kb-file-upload', KbFileUpload);
define('kb-form-control', KbFormControl);
define('kb-form-label', KbFormLabel);
define('kb-icon-button', KbIconButton);
define('kb-input', KbInput);
define('kb-number-input', KbNumberInput);
define('kb-pin-input', KbPinInput);
define('kb-radio', KbRadio);
define('kb-radio-group', KbRadioGroup);
define('kb-rating', KbRating);
define('kb-segment', KbSegment);
define('kb-select', KbSelect);
define('kb-slider', KbSlider);
define('kb-switch', KbSwitch);
define('kb-tags-input', KbTagsInput);
define('kb-textarea', KbTextarea);
define('kb-time-picker', KbTimePicker);
define('kb-box', KbBox);
define('kb-container', KbContainer);
define('kb-divider', KbDivider);
define('kb-flex', KbFlex);
define('kb-grid', KbGrid);
define('kb-scroll-area', KbScrollArea);
define('kb-stack', KbStack);
define('kb-breadcrumb', KbBreadcrumb);
define('kb-link', KbLink);
define('kb-pagination', KbPagination);
define('kb-step', KbStep);
define('kb-steps', KbSteps);
define('kb-tabs', KbTabs);
define('kb-alert-dialog', KbAlertDialog);
define('kb-context-menu', KbContextMenu);
define('kb-drawer', KbDrawer);
define('kb-dropdown-menu', KbDropdownMenu);
define('kb-hover-card', KbHoverCard);
define('kb-menu-item', KbMenuItem);
define('kb-modal', KbModal);
define('kb-popover', KbPopover);
define('kb-tooltip', KbTooltip);
define('kb-blockquote', KbBlockquote);
define('kb-code', KbCode);
define('kb-heading', KbHeading);
define('kb-highlight', KbHighlight);
define('kb-text', KbText);

export const karbitElementsDefined = true;
